# Generated by Django 4.0.3 on 2022-03-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_extras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Extras',
        ),
    ]
