# Generated by Django 4.0.3 on 2022-03-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_delete_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('song', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('genre', models.CharField(max_length=200)),
                ('album', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
